### ISSUE TITLE
Recreating GAN to generate adversarial features.

### ISSUE THREAD

**Issue by RDJ61** [dongtsi/TrafficManipulator#11]
I am pretty new on GAN actually. I already followed all the architecture of GAN and it's parameter from the supplemental.pdf but it seems that I was unable to generate the adversarial features. Can you share the code for the GAN? It would help me a lot if you do because I am trying to understand the contents of your paper.

**Comment by dongtsi** [comment]
https://github.com/dongtsi/TrafficManipulator/issues/4 Please refer to this one. Thanks.

**Comment by dongtsi** [comment]
https://github.com/dongtsi/TrafficManipulator/issues/4 Please refer to this one. Thanks.
