### ISSUE TITLE
Does this project generate actual simulated traffic packets, i.e., .pcap files? If so, what is the parameter for that?”

### ISSUE THREAD

**Issue by Ankyiuu** [dongtsi/TrafficManipulator#12]

**Comment by dongtsi** [comment]
Hi, Ankyiuu.
This project indeed mutates the original packets, but the current version does not seem to explicitly store the mutated .pcap files. The mutated packets should be stored in `STA_best_pktList` at [here](https://github.com/dongtsi/TrafficManipulator/blob/ebc82f78df8544dfc908dd60f77c5a26d3ae8624/manipulator.py#L174).
