### ISSUE TITLE
How to create mimic_set?

### ISSUE THREAD

**Issue by XXXaBg3619** [dongtsi/TrafficManipulator#13]
According to the previous issues I know that how to create train_ben and test. However I still don't know the exact way to create mimic_set.npy.

**Comment by dongtsi** [comment]
In the original paper, mimic_set is created through GAN-based methods. You can also simply use `train_ben` as the `mimic_set`

**Comment by Rohay-Lee** [comment]
Could I understand it that way: The mimic_set can be obtained by using GAN and inputting the features extracted by AfterImage into the GAN model training.
