### ISSUE TITLE
How do you transform pcap to npy

### ISSUE THREAD

**Issue by helomair** [dongtsi/TrafficManipulator#3]
In example step3, you use test.npy, and in step4 & 5 use test.pcap
I think these two(test.npy & test.pcap) are the same, but I'm wondering how do you transform pcap to npy

**Comment by dongtsi** [comment]
In Kitsune, raw packets (.pcap) need to be **extracted** into well-crafted feature vectors (.npy) before fed into machine learning models.
This extraction is done by a **feature extractor**, which is called _AfterImage_ in Kitsune.
We have implemented the feature extraction of AfterImage in `extractor.py` based on the open-source code of Kitsune
Here is an example: 
`python extractor.py -i ./example/test.pcap -o ./example/test.npy`
