### ISSUE TITLE
How is GAN implemented

### ISSUE THREAD

**Issue by SunEternal** [dongtsi/TrafficManipulator#4]
In the paper, the first step is mainly to utilize GAN. However, I can not see this part in code. Maybe I ignore it.

**Comment by dongtsi** [comment]
We do not include the code of GAN as we use the very simple architecture of GAN, and it is not our contribution in the paper.
You can find the topology of GAN used in our work [here](https://github.com/dongtsi/TrafficManipulator/blob/master/supplemental/supp.pdf). 
Hope this helps.
