### ISSUE TITLE
import AfterImageExtractor.AfterImage as af ModuleNotFoundError: No module named 'AfterImageExtractor.AfterImage'...When i try to compile main.py, I seem cannot find the solution to this kind of error.

### ISSUE THREAD

**Issue by AJNatsu** [dongtsi/TrafficManipulator#5]

**Comment by dongtsi** [comment]
Did you compile the cython file and run main.py under the main path (TrafficManipulator/)?

**Comment by AJNatsu** [comment]
When I compile the AfterImage.pyx file, I got two errors which are "FutureWarning: Cython directive 'language_level' not set" and "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun", is it because I compile with mac?

**Comment by dongtsi** [comment]
You may need to install Cython==0.29.11

**Comment by AJNatsu** [comment]
I seem to have a trouble installing Cython==0.29.11, right now i'm using python 3.10, do i need to change the python version?

**Comment by AJNatsu** [comment]
I have successfully compile the file when i install apple xcode. It seems that for mac to compile cython is to use xcode.
